### PR TITLE
Cozie dev

### PR DESCRIPTION
**Pull request by pjayathissa**

### CODE REVIEW

**Comment by FedericoTartarini** [comment]
@pjayathissa I am getting a bit confused, are these the changes I have proposed? If so I guess I can accept them all.

**Comment by pjayathissa** [comment]
@FedericoTartarini Yup, I think you just need to fix the merge conflicts regarding the  `README.md`

**Comment by FedericoTartarini** [comment]
@pjayathissa to be honest I am not understanding what I need to do. This repository in my opinion is getting too messy and I do not know how to manage it. I think I have fixed the issues locally but I cannot push to the repository since it is blocked.

**Comment by pjayathissa** [comment]
Uploaded for review at the fitbitstore

**Pull request merged**
